name: issue-workflow
on: 
  issues:
    types: [opened, edited, closed]
jobs:
  output:
    runs-on: ubuntu-latest
    steps:
      - name: show output
        run: echo ${{  github.event.issue.number }}