name: push-workflow
on: push
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node-modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run build
        run: |
          echo "Building project..."
          npm run build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node-modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run lint
        run: |
          echo "Linting..."
          npm run lint
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: node-modules
          key: node-modules-${{ hashFiles('**/package-lock.json') }}      
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Run Tests
        run: |
          echo "Running unit tests..."
          npm test

  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Output content
        run: ls
      - name: Run deploy
        run: |
          echo "Deploying..."


  