name: push-workflow
on: push
jobs:
  build:
     runs-on: ubuntu-latest
     steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: |
          echo "Building project..."
          npm run build
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: dist
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run lint
        run: |
          echo "Linting..."
          npm run lint
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run Tests
        run: |
          echo "Running unit tests..."
          npm test

  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Get repo
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install  
      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Run deploy
        run: |
          echo "Deploying..."
          ls


  